/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zju_beggar_service_ProcessInfoService */

#ifndef _Included_zju_beggar_service_ProcessInfoService
#define _Included_zju_beggar_service_ProcessInfoService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zju_beggar_service_ProcessInfoService
 * Method:    getProcessInformationNative
 * Signature: ()[[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_zju_beggar_service_ProcessInfoService_getProcessInformationNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
